### ISSUE TITLE
Upload just xml fails when not selecting state folder

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats-Tools#19]
Steps to reproduce:
open tool using arccatalog
fill in Descriptioin, aws access key, secret key, name and temproary workspace location.
fill in xml to upload (leaving state/region folder empty)
select ok.
results in following error
```2019-05-09 06:24:47,588 Error parsing data Traceback (most recent call last):
  File "C:\Users\jknewson\Downloads\StreamStats_ArcToolbox_04292019\ParseData.py", line 61, in __run__
  File "C:\Python27\ArcGIS10.5\Lib\ntpath.py", line 208, in basename
    return split(p)[1]
  File "C:\Python27\ArcGIS10.5\Lib\ntpath.py", line 180, in split
    d, p = splitdrive(p)
  File "C:\Python27\ArcGIS10.5\Lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()```

**Comment by jknewson** [comment]
Filling in state folder location mutes the error

**Comment by kjacobsen16** [comment]
I'm unable to replicate this issue with my latest version, try the version currently on drive
